name: Build Executable

on:
  push:
    branches:
      - Seconde-Partie # Exécuter uniquement sur cette branche
  workflow_dispatch: # Permet d'exécuter manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --add-data "img/skins/*:img/skins" main.py

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/main.exe  # Chemin du fichier généré
