name: Build and Release Warship-Battle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Warship-Battle
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Supporte Linux, macOS et Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup C++ Build Environment
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential g++
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install gcc  # Installe GCC sur macOS
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install mingw  # Installe MinGW sur Windows
          fi

      - name: Build the project
        run: |
          make  # Assurez-vous que votre Makefile est bien configuré

      - name: List files in output directory
        run: ls -l ./out  # Vérifiez que le fichier exécutable existe

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            This is the release of Warship-Battle version v${{ github.run_number }}.
          draft: false
          prerelease: false

      - name: Upload Executable
        id: upload_executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ${{ if eq(matrix.os, 'windows-latest') }}:
              ./out/warship.exe  # Exécutable pour Windows
            ${{ else }}:
              ./out/warship  # Exécutable pour macOS et Linux
          asset_name: |
            ${{ if eq(matrix.os, 'windows-latest') }}:
              warship.exe
            ${{ else }}:
              warship
          asset_content_type: application/octet-stream  # Type MIME générique pour les exécutables
